# Generated by Django 4.2.2 on 2023-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_dailyinspiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinspiration',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
