version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py collectstatic --noinput && 
      python manage.py makemigrations && 
      python manage.py migrate && 
      gunicorn veriprofile.asgi:application -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  staticfiles:
