# Generated by Django 4.2.2 on 2023-10-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='notification',
            name='hr_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hruser'),
        ),
    ]
