# Generated by Django 4.2.2 on 2023-10-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ping_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='sender',
        ),
    ]
