# Generated by Django 4.2.2 on 2023-10-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_ping_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_pings', to='app.employee'),
        ),
    ]
