# Generated by Django 4.2.2 on 2023-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ping_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
