# Generated by Django 4.2.2 on 2023-10-14 07:04

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gallery_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='causes_and_interest',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Open_Source_Projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Patents_or_intellectual_property',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='artifacts_or_creative_works',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='availability_for_networking',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='awards_in_non_professional_fields',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='books_authored',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='business_ventures',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='case_studies',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='challenging_problem_solving_scenarios',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='charitable_initiatives',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='community_leadership_roles',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='competitions_or_challenges_won',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='complex_projects_overcome',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='conference_talks',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='degrees',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='entrepreneurial_achievements',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gitHub_repository_links',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gpa_academic_achivements',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='graduation_dates',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hackathons_won',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='industry_categories',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='industry_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='innovations_in_products',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='institutions_attended',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_address_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_certificate_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_competency_verification_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_contributions_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_endorsement_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_exemplary_profile_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_hr_assessment_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_job_history_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_language_proficiency_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_nationality_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_non_criminal_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_previous_employment_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_qualification_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_recognition_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_reference_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_resume_cv_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_safe_profile_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_skillset_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_social_media_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_work_record_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='join_veriprofile_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='languages_known',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leadership_roles',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='licenses',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='links_to_gitHub',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='magazine_articles',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mentorship_programs_participated_in',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='music_composition',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='new_inventions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='online_courses_taught',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='open_source_contributions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='open_source_organizations_joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='panel_discussions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='personal_website',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='professional_memberships',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project_demonstrations_or_Videos',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project_link1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project_link2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project_link3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='prototypes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='published_articles',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='published_research_papers',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='quit_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='research_papers',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='researches',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='soft_skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sports_achievements',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='startups_founded',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='testimonials_or_recommendations',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='unique_visitors',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='volunteer_activities',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='volunteer_work',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='webinar_presentations',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='whitepapers',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='wikipedia',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workshop_facilitations',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workshops_conducted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='writing',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='youtube',
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('marital_status', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('preferred_language', models.CharField(max_length=100, null=True)),
                ('languages_known', models.CharField(max_length=100, null=True)),
                ('wikipedia', models.CharField(max_length=100, null=True)),
                ('personal_website', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('time_zone', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('ted', models.URLField(blank=True, max_length=100, null=True)),
                ('youtube', models.URLField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=100, null=True)),
                ('degrees', models.CharField(blank=True, max_length=100, null=True)),
                ('institutions_attended', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa_academic_achivements', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_dates', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('joining_date', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title1', models.CharField(max_length=200, null=True)),
                ('joining_date1', models.CharField(blank=True, max_length=100, null=True)),
                ('quit_date', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('industry_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('responsibilities', models.CharField(max_length=200, null=True)),
                ('certifications', models.CharField(blank=True, max_length=100, null=True)),
                ('licenses', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.CharField(blank=True, max_length=100, null=True)),
                ('publications', models.CharField(blank=True, max_length=100, null=True)),
                ('researches', models.CharField(blank=True, max_length=100, null=True)),
                ('projects', models.CharField(blank=True, max_length=100, null=True)),
                ('project_link1', models.URLField(blank=True, max_length=100, null=True)),
                ('project_link2', models.URLField(blank=True, max_length=100, null=True)),
                ('project_link3', models.URLField(blank=True, max_length=100, null=True)),
                ('volunteer_work', models.CharField(max_length=300, null=True)),
                ('professional_memberships', models.CharField(max_length=300, null=True)),
                ('availability_for_networking', models.CharField(max_length=300, null=True)),
                ('technical_skills', models.CharField(max_length=100, null=True)),
                ('soft_skills', models.CharField(max_length=100, null=True)),
                ('languages_spoken', models.CharField(max_length=200, null=True)),
                ('hobbies', models.CharField(max_length=200, null=True)),
                ('causes_and_interest', models.CharField(max_length=200, null=True)),
                ('contact_information', models.CharField(max_length=200, null=True)),
                ('published_articles', models.CharField(max_length=300, null=True)),
                ('gitHub_repository_links', models.URLField(blank=True, max_length=100, null=True)),
                ('open_source_contributions', models.CharField(blank=True, max_length=100, null=True)),
                ('case_studies', models.CharField(blank=True, max_length=100, null=True)),
                ('whitepapers', models.CharField(blank=True, max_length=100, null=True)),
                ('research_papers', models.CharField(blank=True, max_length=100, null=True)),
                ('artifacts_or_creative_works', models.CharField(blank=True, max_length=100, null=True)),
                ('project_demonstrations_or_Videos', models.CharField(blank=True, max_length=100, null=True)),
                ('Patents_or_intellectual_property', models.CharField(blank=True, max_length=100, null=True)),
                ('testimonials_or_recommendations', models.CharField(blank=True, max_length=100, null=True)),
                ('Open_Source_Projects', models.CharField(blank=True, max_length=100, null=True)),
                ('links_to_gitHub', models.CharField(blank=True, max_length=100, null=True)),
                ('open_source_organizations_joined', models.CharField(blank=True, max_length=100, null=True)),
                ('conference_talks', models.CharField(blank=True, max_length=100, null=True)),
                ('webinar_presentations', models.CharField(blank=True, max_length=100, null=True)),
                ('workshop_facilitations', models.CharField(blank=True, max_length=100, null=True)),
                ('panel_discussions', models.CharField(blank=True, max_length=100, null=True)),
                ('mentorship_programs_participated_in', models.CharField(max_length=100, null=True)),
                ('online_courses_taught', models.CharField(max_length=100, null=True)),
                ('workshops_conducted', models.CharField(max_length=100, null=True)),
                ('volunteer_activities', models.CharField(max_length=100, null=True)),
                ('charitable_initiatives', models.CharField(max_length=100, null=True)),
                ('community_leadership_roles', models.CharField(max_length=100, null=True)),
                ('innovations_in_products', models.CharField(max_length=300, null=True)),
                ('new_inventions', models.CharField(max_length=300, null=True)),
                ('prototypes', models.CharField(max_length=300, null=True)),
                ('startups_founded', models.CharField(max_length=300, null=True)),
                ('entrepreneurial_achievements', models.CharField(max_length=300, null=True)),
                ('business_ventures', models.CharField(max_length=300, null=True)),
                ('books_authored', models.CharField(max_length=300, null=True)),
                ('published_research_papers', models.CharField(max_length=300, null=True)),
                ('magazine_articles', models.CharField(max_length=300, null=True)),
                ('artwork', models.CharField(max_length=300, null=True)),
                ('music_composition', models.CharField(max_length=300, null=True)),
                ('writing', models.CharField(max_length=300, null=True)),
                ('challenging_problem_solving_scenarios', models.CharField(max_length=300, null=True)),
                ('complex_projects_overcome', models.CharField(max_length=300, null=True)),
                ('hackathons_won', models.CharField(max_length=300, null=True)),
                ('competitions_or_challenges_won', models.CharField(max_length=300, null=True)),
                ('sports_achievements', models.CharField(max_length=300, null=True)),
                ('leadership_roles', models.CharField(max_length=300, null=True)),
                ('awards_in_non_professional_fields', models.CharField(max_length=300, null=True)),
                ('industry_categories', models.CharField(max_length=300, null=True)),
                ('portfolio', models.CharField(max_length=100, null=True)),
                ('current_position', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.CharField(max_length=1000, null=True)),
                ('unique_id', models.CharField(max_length=100, null=True, unique=True)),
                ('unique_visitors', models.JSONField(default=list)),
                ('is_address_verified', models.BooleanField(default=False)),
                ('is_previous_employment_verified', models.BooleanField(default=False)),
                ('is_job_history_verified', models.BooleanField(default=False)),
                ('is_recognition_verified', models.BooleanField(default=False)),
                ('is_reference_verified', models.BooleanField(default=False)),
                ('is_nationality_verified', models.BooleanField(default=False)),
                ('is_qualification_verified', models.BooleanField(default=False)),
                ('is_certificate_verified', models.BooleanField(default=False)),
                ('is_endorsement_verified', models.BooleanField(default=False)),
                ('is_work_record_verified', models.BooleanField(default=False)),
                ('is_contributions_verified', models.BooleanField(default=False)),
                ('is_non_criminal_verified', models.BooleanField(default=False)),
                ('is_exemplary_profile_verified', models.BooleanField(default=False)),
                ('is_safe_profile_verified', models.BooleanField(default=False)),
                ('is_resume_cv_verified', models.BooleanField(default=False)),
                ('is_skillset_verified', models.BooleanField(default=False)),
                ('is_hr_assessment_verified', models.BooleanField(default=False)),
                ('is_competency_verification_verified', models.BooleanField(default=False)),
                ('is_social_media_verified', models.BooleanField(default=False)),
                ('is_language_proficiency_verified', models.BooleanField(default=False)),
                ('join_veriprofile_at', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Not-verified', max_length=200)),
                ('profile_created_by', models.CharField(max_length=200, null=True)),
                ('cover_image', models.ImageField(default=app.models.default_cover_image, upload_to='covers/')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='pics/')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
