# Generated by Django 4.2.2 on 2023-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_causes_and_interest_employee_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='unique_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
