# Generated by Django 4.2.2 on 2023-10-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_registration_unique_id_employee_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='c_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
