# Generated by Django 4.2.2 on 2023-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_charitable_initiatives_registration_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='skill_filed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
