# Generated by Django 4.2.2 on 2023-10-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_registration_skill_filed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='time_zone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
