# Generated by Django 4.2.2 on 2023-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_registration_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='current_business',
        ),
        migrations.AddField(
            model_name='registration',
            name='innovation_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
