# Generated by Django 4.2.2 on 2023-10-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_employee_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='update_status',
            field=models.BooleanField(default=False),
        ),
    ]
