# Generated by Django 4.2.2 on 2023-10-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='college',
        ),
    ]
