# Generated by Django 4.2.2 on 2023-10-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_additionalqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('joining_date', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_id', models.ImageField(blank=True, null=True, upload_to='occupation/')),
            ],
        ),
    ]
