# Generated by Django 4.2.2 on 2023-10-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_jobs_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upload_id',
        ),
    ]
