# Generated by Django 4.2.2 on 2023-10-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_employee_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_job_title', models.CharField(max_length=200, null=True)),
                ('ex_company_name', models.CharField(max_length=200, null=True)),
                ('ex_joining_date', models.CharField(blank=True, max_length=100, null=True)),
                ('ex_quit_date', models.CharField(blank=True, max_length=100, null=True)),
                ('ex_upload_id', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('ex_job_location', models.CharField(max_length=200, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
