# Generated by Django 4.2.2 on 2023-10-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100, null=True)),
                ('honors', models.CharField(blank=True, max_length=100, null=True)),
                ('honor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('awards_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='additional_info_input',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='awards_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='degrees',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ex_company_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ex_job_location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ex_job_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ex_joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ex_quit_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ex_upload_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='honor_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='honors',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='social',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='youtube',
        ),
    ]
