# Generated by Django 4.2.2 on 2023-10-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_honors_remove_employee_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100, null=True)),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_filed', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skill_filed',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skill_name',
        ),
    ]
