# Generated by Django 4.2.2 on 2023-10-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_skills_remove_employee_skill_filed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100, null=True)),
                ('proof_of_work', models.CharField(max_length=300, null=True)),
                ('proof_of_work_input', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='proof_of_work',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='proof_of_work_input',
        ),
    ]
