# Generated by Django 4.2.2 on 2023-10-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_honors_employee_alter_proofofwork_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honors',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='proofofwork',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='socialwork',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Honors',
        ),
        migrations.DeleteModel(
            name='ProofOfWork',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='SocialWork',
        ),
    ]
