# Generated by Django 4.2.2 on 2023-10-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_honors_employee_remove_proofofwork_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_work', models.CharField(max_length=100, null=True)),
                ('social_work_input', models.CharField(max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_filed', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_work', models.CharField(max_length=300, null=True)),
                ('proof_of_work_input', models.CharField(max_length=300, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Honors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honors', models.CharField(blank=True, max_length=100, null=True)),
                ('honor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('awards_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_job_title', models.CharField(max_length=200, null=True)),
                ('ex_company_name', models.CharField(max_length=200, null=True)),
                ('ex_joining_date', models.CharField(blank=True, max_length=100, null=True)),
                ('ex_quit_date', models.CharField(blank=True, max_length=100, null=True)),
                ('ex_upload_id', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('ex_job_location', models.CharField(max_length=200, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
