# Generated by Django 4.2.2 on 2023-10-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_socialwork_skills_proofofwork_honors_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_inovation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='innovation_link',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='innovation_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='proof_of_concept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reference_contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upload_info_certificate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upload_info_image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upload_info_video',
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_name', models.CharField(max_length=200, null=True)),
                ('proof_of_concept', models.CharField(max_length=200, null=True)),
                ('upload_info_video', models.ImageField(null=True, upload_to='innovationvid/')),
                ('upload_info_image', models.ImageField(null=True, upload_to='innovationimg/')),
                ('date_of_inovation', models.CharField(max_length=200, null=True)),
                ('upload_info_certificate', models.ImageField(null=True, upload_to='innovationcer/')),
                ('innovation_link', models.CharField(max_length=200, null=True)),
                ('reference_name', models.CharField(max_length=200, null=True)),
                ('reference_contact', models.CharField(max_length=200, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
