# Generated by Django 4.2.2 on 2023-10-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_employee_date_of_inovation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='college',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
