# Generated by Django 4.2.2 on 2023-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_jobs_job_industry_jobs_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='honors',
            name='awards_given_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
