# Generated by Django 4.2.2 on 2023-10-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_mediareferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediareferences',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
