# Generated by Django 4.2.2 on 2023-11-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_employee_is_address_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
