# Generated by Django 4.2.2 on 2023-11-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-schedule_time']},
        ),
    ]
