# Generated by Django 4.2.2 on 2023-11-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-broadcast_on']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='schedule_time',
            new_name='broadcast_on',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read_status',
            new_name='sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Recipients',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='custom_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='custom_frequency_end_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='custom_frequency_start_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='frequency_option',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='hr_users',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
